/**
 * TranscriptFeed — scrolling log of voice conversation turns.
 *
 * User utterances align left; assistant responses (future: generated by LLM
 * and echoed back via the voice session) align right.  Partial transcripts
 * are shown in muted italic until finalised.
 */

import { useEffect, useRef } from 'react';
import { TranscriptTurn } from '../../../lib/useVoiceSession';

interface TranscriptFeedProps {
  turns: TranscriptTurn[];
}

export function TranscriptFeed({ turns }: TranscriptFeedProps) {
  const bottomRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to the latest turn.
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [turns.length]);

  if (turns.length === 0) {
    return (
      <div
        className="flex items-center justify-center h-full text-[11px] opacity-40 font-mono"
        style={{ color: '#22d3ee' }}
      >
        awaiting speech…
      </div>
    );
  }

  return (
    <div className="h-full min-h-0 overflow-y-auto flex flex-col gap-1 pr-1">
      {turns.map((turn, i) => (
        <TurnRow key={i} turn={turn} />
      ))}
      <div ref={bottomRef} />
    </div>
  );
}

function TurnRow({ turn }: { turn: TranscriptTurn }) {
  const isUser = turn.role === 'user';
  const accentColor = isUser ? '#22d3ee' : '#a78bfa';

  return (
    <div className={`flex flex-col gap-0.5 ${isUser ? 'items-start' : 'items-end'}`}>
      {/* Role chip */}
      <span
        className="text-[9px] font-mono uppercase tracking-widest"
        style={{ color: `${accentColor}88` }}
      >
        {isUser ? 'you' : 'jarvis'}
      </span>
      {/* Bubble */}
      <div
        className="max-w-[92%] px-2 py-1 rounded text-[11px] leading-snug"
        style={{
          background: `${accentColor}12`,
          border: `1px solid ${accentColor}28`,
          color: turn.partial ? `${accentColor}88` : '#d7f6ff',
          fontStyle: turn.partial ? 'italic' : 'normal',
          transition: 'color 0.2s ease',
        }}
      >
        {turn.text}
      </div>
    </div>
  );
}
